In [23]:
### Ініціаліхація бібліотек

In [24]:
import random as rnd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
def print_array_info(arra):
    color = 'green'
    print('Array:', colored(arra, color))
    print('Size:', colored(arra.size, color), 'equals length', colored(len(arra), color))
    print('Shape:', colored(arra.shape, color))
    print('Data type:', colored(arra.dtype, color))
    print('Dimention count:', colored(arra.ndim, color))

In [26]:

### Завдання 1
### NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
### CRUD

In [27]:
print("///////////////////////////////////////////")
print("Create")
array = np.arange(0, 225, 5)
print("///////////////////////////////////////////")
print("Read")
print()
print(array)
print("///////////////////////////////////////////")
print("Update")
print()
array = np.insert(array, 25, 25)
print(array)
print("///////////////////////////////////////////")
print("Delete")
print()
array = np.delete(array, 0)
print(array)
print("///////////////////////////////////////////")
print("Using random")
print()
secondArray = np.random.randint(25, size=(array.size))
print(secondArray)
print("///////////////////////////////////////////")

///////////////////////////////////////////
Create
///////////////////////////////////////////
Read

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Update

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120  25 125 130 135 140 145 150 155 160 165 170
 175 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Delete

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120  25 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Using random

[ 2 20 12  6 18 14  7  3  6 17  4  5 17 22  3 13  5  2 19 22 14  7 20  1
  2 13  2 20 10 10 23 23 16 24 23 15  9 16 10  9  4 20 24 11 17]
///////////////////////////////////////////

In [28]:
### Матриця

In [29]:
print("///////////////////////////////////////////")
print("Create")
matrix = np.arange(16).reshape(4, 4)
print("///////////////////////////////////////////")
print("Read")
print()
print(matrix)
print("///////////////////////////////////////////")
print("Update")
print()
newrow = [25,25,25,25]
row_n = matrix.shape[0] ##last row
matrix = np.insert(matrix,row_n,[newrow],axis= 0)
print(matrix)
print("///////////////////////////////////////////")
print("Delete")
print()
matrix = np.delete(matrix, 0, 0)
print(matrix)
print("///////////////////////////////////////////")

///////////////////////////////////////////
Create
///////////////////////////////////////////
Read

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
///////////////////////////////////////////
Update

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [19 19 19 19]]
///////////////////////////////////////////
Delete

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [19 19 19 19]]
///////////////////////////////////////////
