In [1]:
### Ініціаліхація бібліотек

In [2]:
import random as rnd
import numpy as np
import pandas as pd
import matplotlib.pyplot as mat

In [3]:
def butify_print(message, data):
    print("===========================================")
    print(message)
    print()
    print(data)
    print("===========================================")

def yhat(x, y):
    k, b = np.polyfit(x, y, 1)
    y_pred = k*x + b
    return y_pred

In [4]:

### Завдання 1
### NumPy (створити набір даних (розмір за власним рішенням), провести CRUD операції над даними (скаляр, вектор, матриця)). Використати arange, random.
### CRUD

In [5]:
print("///////////////////////////////////////////")
print("Create")
array = np.arange(0, 225, 5)
print("///////////////////////////////////////////")
print("Read")
print()
print(array)
print("///////////////////////////////////////////")
print("Update")
print()
array = np.insert(array, 25, 25)
print(array)
print("///////////////////////////////////////////")
print("Delete")
print()
array = np.delete(array, 0)
print(array)
print("///////////////////////////////////////////")
print("Using random")
print()
secondArray = np.random.randint(25, size=(array.size))
print(secondArray)
print("///////////////////////////////////////////")

///////////////////////////////////////////
Create
///////////////////////////////////////////
Read

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Update

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120  25 125 130 135 140 145 150 155 160 165 170
 175 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Delete

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120  25 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220]
///////////////////////////////////////////
Using random

[ 3 21  9  0 18  1 14  0 24  2 18  1  6  1  4 15 13 20  1 21 22 21 14 16
 15  2  4 16  8 20 21 23  9 24 11 12  9 16  2 19 13  5 23 16  2]
///////////////////////////////////////////

In [6]:
### Матриця

In [7]:
matrix = np.arange(16).reshape(4, 4)
butify_print("Create and Read", matrix)
print("///////////////////////////////////////////")
newrow = [19,19,19,19]
row_n = matrix.shape[0] ##last row
matrix = np.insert(matrix,row_n,[newrow],axis= 0)
matrix = np.arange(16).reshape(4, 4)
butify_print("Update", matrix)
print("///////////////////////////////////////////")
matrix = np.delete(matrix, 0, 0)
butify_print("Delete", matrix)
print("///////////////////////////////////////////")

Create and Read

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
///////////////////////////////////////////
Update

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
///////////////////////////////////////////
Delete

[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
///////////////////////////////////////////


#Вектори

In [8]:
firstArray = np.arange(0,15,3)
secondArray = np.random.randint(19, size=5)

thirdArray = np.add(firstArray,secondArray)
butify_print("Add", f"{firstArray}\n       + \n{secondArray}\n       = \n{thirdArray}")

fourthArray = np.subtract(thirdArray,secondArray)
butify_print("Subtract", f"{thirdArray}\n       - \n{secondArray}\n       = \n{fourthArray}")

Add

[ 0  3  6  9 12]
       + 
[12  6 14 13 18]
       = 
[12  9 20 22 30]
Subtract

[12  9 20 22 30]
       - 
[12  6 14 13 18]
       = 
[ 0  3  6  9 12]


In [9]:
### Завдання 2
### Pandas (створити dataframe різними способами, провести маніпуляції з даними (head, describe, iloc, loc ...))

In [10]:
data = pd.read_csv("FyntraCustomerData.csv")
data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'FyntraCustomerData.csv'

In [ ]:
data.describe()

In [ ]:
print(data.iloc[0])

In [ ]:
print(data.loc[0:19,"Avatar"])

In [ ]:
### Завдання 3
### Matplotlib (створити набір даних лінійної функції з урахуванням помилок вимірювань, побудувати графік функції та згенерованих даних, обчислити похибку з використанням метрик MAE, MSE). Записати отримані результати у csv файл (формат: X,Y, Y_hat, mAE, mSE)

In [ ]:
mat.rcParams['figure.figsize'] = (10, 5)
fig = mat.subplots()

In [ ]:
%matplotlib inline
mat.rcParams['figure.figsize'] = (10, 5)
mat.style.use('seaborn-deep')
x_data = []
y_data = []
for i in np.arange(0,35,0.35):
    x_data.append(i)
    y_data.append(i**2)
X = np.linspace(0,15,500)
Y = X
X1 = np.linspace(0,65,9000)
Y1 = X1*19
fig, ax = mat.subplots()
mat.plot(x_data,y_data,X,Y,X1,Y1)

In [ ]:
mat.rcParams['figure.figsize'] = (10, 5)
mat.scatter(x_data,y_data)

In [ ]:
mean = np.mean(x_data)
MAE = [np.abs(real - mean) for real in x_data]
MSE = [np.square(real - mean) for real in x_data]

x_data = np.random.random(19)
y_data = x_data**2

y_hat = (yhat(x_data, y_data))


head = np.column_stack((x_data,y_data, y_hat, MAE, MSE))
tbl = pd.DataFrame(head, columns=('X', 'Y', 'Y_Hat', 'MAE', 'MSE'))
print(tbl)

In [ ]:
tbl.to_csv('data.csv')